name: MacOS Build and Test

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'doc/**'
      - 'docker/**'
      - 'traces/**'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'docker/**'
      - 'traces/**'
      - '.vscode/**'

jobs:
  macos-cmake:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set Git http.postBuffer to something high
        run: git config --global http.postBuffer 524288000

      - name: Handle homebrew quirks
        run: rm -rf /usr/local/bin/2to3

      - name: Update brew repos
        run: brew update
        continue-on-error: true

      - name: Tap RfidResearchGroup/proxmark3
        run: brew tap RfidResearchGroup/proxmark3

      - name: Install dependencies
        run: brew install readline coreutils qt@5 RfidResearchGroup/proxmark3/arm-none-eabi-gcc openssl gd
        continue-on-error: true

      - name: Install Python dependencies
        run: pip install -r tools/requirements.txt

      - name: Prepare Build Folders
        run: |
          mkdir -p client/build
          ln -s ../cmdscripts client/build/
          ln -s ../luascripts client/build/
          ln -s ../pyscripts client/build/
          ln -s ../lualibs client/build/

      - name: Initiate cmake environment
        run: cmake --version

      - name: Build
        env:
          VERBOSE: 1
        run: make -j$((`sysctl -n hw.ncpu` + 1))

      - name: Test
        env:
          CHECKARGS: "--clientbin ./client/build/proxmark3"
        run: make check
